<?php

/**
 * @file
 * Workbench View module file.
 */

/**
 * Implements hook_node_grants().
 */
function workbench_view_node_grants($account, $op) {
  $grants = array();
  
  if ($op == 'view') {
    $query = db_select('workbench_access_user', 'wau')
        ->fields('wau', array('access_id'))
        ->condition('wau.uid', $account->uid);
    $result = $query->execute()->fetchCol(0);
    
    $grants['workbench_access_node_view'] = $result;
  }

  return $grants;
}


/**
 * Implements hook_node_access_records().
 */
function workbench_view_node_access_records($node) {
  $grants = array();
    
  if(isset($node->workbench_access) && !empty($node->workbench_access) && !$node->status) {
    foreach($node->workbench_access as $section) {
      $grants[] = array(
        'realm' => 'workbench_access_node_view',
        'gid' => $section,
        'grant_view' => 1,
        'grant_update' => 0,
        'grant_delete' => 0,
        'priority' => 1,
      );
    }
  }

  return $grants;
}
