<?php
function _get_node_export_nodes_one() {
return array(
  array(
    'nid' => '14',
    'type' => 'article',
    'language' => '',
    'uid' => '1',
    'status' => '1',
    'created' => '1284400449',
    'changed' => 1367445932,
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '14',
    'revision_uid' => '1',
    'title' => 'Article 5',
    'body' => '',
    'teaser' => '',
    'revision_timestamp' => '1284400449',
    'format' => '0',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:2:{s:13:"form_build_id";s:37:"form-f648e06cda4c2e66b056ea83ccf5e0c5";s:7:"contact";i:0;}',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
      '3' => array(
        'value' => 'page_image',
      ),
      '4' => array(
        'value' => 'page_image',
      ),
      '5' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '28',
        'uid' => '1',
        'filename' => 'aug_image5_1.png',
        'filepath' => 'sites/default/files/aug_image5_1.png',
        'filemime' => 'image/png',
        'filesize' => '278292',
        'status' => '1',
        'timestamp' => '1284400355',
        'origname' => 'aug_image5_1.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '29',
        'uid' => '1',
        'filename' => 'aug_image5_2.png',
        'filepath' => 'sites/default/files/aug_image5_2.png',
        'filemime' => 'image/png',
        'filesize' => '441957',
        'status' => '1',
        'timestamp' => '1284400367',
        'origname' => 'aug_image5_2.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '30',
        'uid' => '1',
        'filename' => 'aug_image5_3.png',
        'filepath' => 'sites/default/files/aug_image5_3.png',
        'filemime' => 'image/png',
        'filesize' => '328302',
        'status' => '1',
        'timestamp' => '1284400378',
        'origname' => 'aug_image5_3.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '3' => array(
        'fid' => '31',
        'uid' => '1',
        'filename' => 'aug_image5_4.png',
        'filepath' => 'sites/default/files/aug_image5_4.png',
        'filemime' => 'image/png',
        'filesize' => '358471',
        'status' => '1',
        'timestamp' => '1284400389',
        'origname' => 'aug_image5_4.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '4' => array(
        'fid' => '32',
        'uid' => '1',
        'filename' => 'aug_image5_4.png',
        'filepath' => 'sites/default/files/aug_image5_4_0.png',
        'filemime' => 'image/png',
        'filesize' => '358471',
        'status' => '1',
        'timestamp' => '1284400413',
        'origname' => 'aug_image5_4.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '5' => array(
        'fid' => '34',
        'uid' => '1',
        'filename' => 'aug_image5_6.png',
        'filepath' => 'sites/default/files/aug_image5_6.png',
        'filemime' => 'image/png',
        'filesize' => '421277',
        'status' => '1',
        'timestamp' => '1284400444',
        'origname' => 'aug_image5_6.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '27',
        'uid' => '1',
        'filename' => 'aug_image5_1_thumb.png',
        'filepath' => 'sites/default/files/aug_image5_1_thumb.png',
        'filemime' => 'image/png',
        'filesize' => '17295',
        'status' => '1',
        'timestamp' => '1284400345',
        'origname' => 'aug_image5_1_thumb.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => NULL,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => 2584903,
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
      '1' => NULL,
      '2' => NULL,
      '3' => NULL,
      '4' => array(
        'fid' => '33',
        'uid' => '1',
        'filename' => 'aug_image5_5.png',
        'filepath' => 'sites/default/files/aug_image5_5.png',
        'filemime' => 'image/png',
        'filesize' => '380838',
        'status' => '1',
        'timestamp' => '1284400430',
        'origname' => 'aug_image5_5.png',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1284400449',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'uuid' => '3e4a0c60-b2ab-11e2-b13b-13c9b9442900',
    'is_new' => FALSE,
    'timestamp' => 1367445932,
    'xmlsitemap' => array(
      'type' => 'node',
      'id' => '14',
      'subtype' => 'article',
      'status' => 0,
      'status_default' => 0,
      'status_override' => 0,
      'priority' => 0.5,
      'priority_default' => 0.5,
      'priority_override' => 0,
      'changefreq' => 0,
      'changecount' => 0,
      'loc' => 'node/14',
      'lastmod' => '1367445932',
      'access' => TRUE,
      'language' => '',
    ),
    'uri' => array(
      'path' => 'node/14',
      'options' => array(),
    ),
    'path' => 'content/articles/article-5',
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
}