<?php
function _get_node_export_nodes_one() {
return array(
  array(
    'nid' => '61364',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1361895359',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61364',
    'revision_uid' => '1',
    'title' => 'cover_ee_0213',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/coveree0213',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '12906',
        'uid' => '5392',
        'filename' => 'cover1_ee_0213.png',
        'filepath' => 'sites/default/files/cover1_ee_0213.png',
        'filemime' => 'image/png',
        'filesize' => '361458',
        'status' => '1',
        'timestamp' => '1361895358',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '12603',
        'uid' => '5392',
        'filename' => 'cover2_0213.png',
        'filepath' => 'sites/default/files/cover2_0213.png',
        'filemime' => 'image/png',
        'filesize' => '474300',
        'status' => '1',
        'timestamp' => '1360945162',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '12604',
        'uid' => '5392',
        'filename' => 'cover3_0213.png',
        'filepath' => 'sites/default/files/cover3_0213.png',
        'filemime' => 'image/png',
        'filesize' => '578771',
        'status' => '1',
        'timestamp' => '1360945162',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '12905',
        'uid' => '5392',
        'filename' => 'cover1_ee_tb_0213.png',
        'filepath' => 'sites/default/files/cover1_ee_tb_0213.png',
        'filemime' => 'image/png',
        'filesize' => '39770',
        'status' => '1',
        'timestamp' => '1361895358',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1454299',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1361895359',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '61365',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1361897456',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61365',
    'revision_uid' => '1',
    'title' => 'ad_eso_abc2_0213',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/adesoabc20213',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '12908',
        'uid' => '5392',
        'filename' => 'ad_eso_abc2_0213.png',
        'filepath' => 'sites/default/files/ad_eso_abc2_0213.png',
        'filemime' => 'image/png',
        'filesize' => '388523',
        'status' => '1',
        'timestamp' => '1361897456',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '12907',
        'uid' => '5392',
        'filename' => 'ad_eso_abc2_tb_0213.png',
        'filepath' => 'sites/default/files/ad_eso_abc2_tb_0213.png',
        'filemime' => 'image/png',
        'filesize' => '47002',
        'status' => '1',
        'timestamp' => '1361897456',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '435525',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1361897456',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56292',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1362601064',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56292',
    'revision_uid' => '1',
    'title' => 'europers2_0213',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/europers20213',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
      '3' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13033',
        'uid' => '5392',
        'filename' => 'europers2_1_0213.png',
        'filepath' => 'sites/default/files/europers2_1_0213.png',
        'filemime' => 'image/png',
        'filesize' => '599356',
        'status' => '1',
        'timestamp' => '1362601063',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13034',
        'uid' => '5392',
        'filename' => 'europers2_2_0213.png',
        'filepath' => 'sites/default/files/europers2_2_0213.png',
        'filemime' => 'image/png',
        'filesize' => '745950',
        'status' => '1',
        'timestamp' => '1362601064',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13035',
        'uid' => '5392',
        'filename' => 'europers2_3_0213.png',
        'filepath' => 'sites/default/files/europers2_3_0213.png',
        'filemime' => 'image/png',
        'filesize' => '757988',
        'status' => '1',
        'timestamp' => '1362601064',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '3' => array(
        'fid' => '13036',
        'uid' => '5392',
        'filename' => 'europers2_4_0213.png',
        'filepath' => 'sites/default/files/europers2_4_0213.png',
        'filemime' => 'image/png',
        'filesize' => '328779',
        'status' => '1',
        'timestamp' => '1362601064',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13032',
        'uid' => '5392',
        'filename' => 'europers2_0213.png',
        'filepath' => 'sites/default/files/europers2_0213.png',
        'filemime' => 'image/png',
        'filesize' => '26025',
        'status' => '1',
        'timestamp' => '1362601063',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '2458098',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1362601064',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(
      'tags' => array(
        '1' => 'European Perspectives',
      ),
    ),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56477',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1362768501',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56477',
    'revision_uid' => '1',
    'title' => 'CP_ASCOGU_cover_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/cpascogucover0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13066',
        'uid' => '5392',
        'filename' => 'cp_asco_gu_cover_0313.png',
        'filepath' => 'sites/default/files/cp_asco_gu_cover_0313.png',
        'filemime' => 'image/png',
        'filesize' => '254696',
        'status' => '1',
        'timestamp' => '1362768501',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13065',
        'uid' => '5392',
        'filename' => 'cp_asco_gu_cover_tb_0313.png',
        'filepath' => 'sites/default/files/cp_asco_gu_cover_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '33126',
        'status' => '1',
        'timestamp' => '1362768501',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '287822',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1362768501',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56713',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363028880',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56713',
    'revision_uid' => '1',
    'title' => 'sctm_cover_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmcover0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13132',
        'uid' => '5392',
        'filename' => 'sctm_cover_0313.png',
        'filepath' => 'sites/default/files/sctm_cover_0313.png',
        'filemime' => 'image/png',
        'filesize' => '592155',
        'status' => '1',
        'timestamp' => '1363028880',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13131',
        'uid' => '5392',
        'filename' => 'sctm_cover_tb_0313.png',
        'filepath' => 'sites/default/files/sctm_cover_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '61026',
        'status' => '1',
        'timestamp' => '1363028879',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '653181',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363028880',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56714',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363028958',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56714',
    'revision_uid' => '1',
    'title' => 'sctm_abstracts_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmabstracts0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13134',
        'uid' => '5392',
        'filename' => 'sctm_abstracts1_0313.png',
        'filepath' => 'sites/default/files/sctm_abstracts1_0313.png',
        'filemime' => 'image/png',
        'filesize' => '720990',
        'status' => '1',
        'timestamp' => '1363028957',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13135',
        'uid' => '5392',
        'filename' => 'sctm_abstracts2_0313.png',
        'filepath' => 'sites/default/files/sctm_abstracts2_0313.png',
        'filemime' => 'image/png',
        'filesize' => '747749',
        'status' => '1',
        'timestamp' => '1363028958',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13136',
        'uid' => '5392',
        'filename' => 'sctm_abstracts3_0313.png',
        'filepath' => 'sites/default/files/sctm_abstracts3_0313.png',
        'filemime' => 'image/png',
        'filesize' => '718539',
        'status' => '1',
        'timestamp' => '1363028958',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13133',
        'uid' => '5392',
        'filename' => 'sctm_abstracts_tb_0412.png',
        'filepath' => 'sites/default/files/sctm_abstracts_tb_0412_11.png',
        'filemime' => 'image/png',
        'filesize' => '29809',
        'status' => '1',
        'timestamp' => '1363028957',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '2217087',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363028958',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56716',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363030125',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56716',
    'revision_uid' => '1',
    'title' => 'sctm_news_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmnews0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13138',
        'uid' => '5392',
        'filename' => 'sctm_news1_0313.png',
        'filepath' => 'sites/default/files/sctm_news1_0313.png',
        'filemime' => 'image/png',
        'filesize' => '684838',
        'status' => '1',
        'timestamp' => '1363030125',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13139',
        'uid' => '5392',
        'filename' => 'sctm_news2_0313.png',
        'filepath' => 'sites/default/files/sctm_news2_0313.png',
        'filemime' => 'image/png',
        'filesize' => '766717',
        'status' => '1',
        'timestamp' => '1363030125',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13140',
        'uid' => '5392',
        'filename' => 'sctm_news3_0313.png',
        'filepath' => 'sites/default/files/sctm_news3_0313.png',
        'filemime' => 'image/png',
        'filesize' => '672869',
        'status' => '1',
        'timestamp' => '1363030125',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13137',
        'uid' => '5392',
        'filename' => 'sctm_news_tb_0412.png',
        'filepath' => 'sites/default/files/sctm_news_tb_0412_10.png',
        'filemime' => 'image/png',
        'filesize' => '28625',
        'status' => '1',
        'timestamp' => '1363030125',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '2153049',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363030125',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '56973',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363272852',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '56973',
    'revision_uid' => '1',
    'title' => 'cover_ch_1111',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/coverch1111',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13172',
        'uid' => '5392',
        'filename' => 'cover_ch_1111.png',
        'filepath' => 'sites/default/files/cover_ch_1111.png',
        'filemime' => 'image/png',
        'filesize' => '482006',
        'status' => '1',
        'timestamp' => '1363272852',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13171',
        'uid' => '5392',
        'filename' => 'cover_ch_tb_1111.png',
        'filepath' => 'sites/default/files/cover_ch_tb_1111.png',
        'filemime' => 'image/png',
        'filesize' => '50003',
        'status' => '1',
        'timestamp' => '1363272851',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '532009',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363272852',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '57542',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363793561',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '57542',
    'revision_uid' => '1',
    'title' => 'cover_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/cover0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13256',
        'uid' => '5392',
        'filename' => 'cover1_0313.png',
        'filepath' => 'sites/default/files/cover1_0313.png',
        'filemime' => 'image/png',
        'filesize' => '351915',
        'status' => '1',
        'timestamp' => '1363793560',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13257',
        'uid' => '5392',
        'filename' => 'cover2_0213.png',
        'filepath' => 'sites/default/files/cover2_0213_0.png',
        'filemime' => 'image/png',
        'filesize' => '474300',
        'status' => '1',
        'timestamp' => '1363793560',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13258',
        'uid' => '5392',
        'filename' => 'cover3_0213.png',
        'filepath' => 'sites/default/files/cover3_0213_0.png',
        'filemime' => 'image/png',
        'filesize' => '578771',
        'status' => '1',
        'timestamp' => '1363793560',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13255',
        'uid' => '5392',
        'filename' => 'cover1_tb_0313.png',
        'filepath' => 'sites/default/files/cover1_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '41875',
        'status' => '1',
        'timestamp' => '1363793560',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1446861',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363793561',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '57543',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363793809',
    'changed' => '1367445991',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '57543',
    'revision_uid' => '1',
    'title' => 'abstracts_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445991',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/abstracts0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
      '3' => array(
        'value' => 'page_image',
      ),
      '4' => array(
        'value' => 'page_image',
      ),
      '5' => array(
        'value' => 'page_image',
      ),
      '6' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13260',
        'uid' => '5392',
        'filename' => 'abstracts1_0312.png',
        'filepath' => 'sites/default/files/abstracts1_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '442370',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13261',
        'uid' => '5392',
        'filename' => 'abstracts2_0312.png',
        'filepath' => 'sites/default/files/abstracts2_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '456592',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13262',
        'uid' => '5392',
        'filename' => 'abstracts3_0312.png',
        'filepath' => 'sites/default/files/abstracts3_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '475592',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '3' => array(
        'fid' => '13263',
        'uid' => '5392',
        'filename' => 'abstracts4_0312.png',
        'filepath' => 'sites/default/files/abstracts4_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '352047',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '4' => array(
        'fid' => '13264',
        'uid' => '5392',
        'filename' => 'abstracts5_0312.png',
        'filepath' => 'sites/default/files/abstracts5_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '382583',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '5' => array(
        'fid' => '13265',
        'uid' => '5392',
        'filename' => 'abstracts6_0312.png',
        'filepath' => 'sites/default/files/abstracts6_0312_0.png',
        'filemime' => 'image/png',
        'filesize' => '460435',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '6' => array(
        'fid' => '13266',
        'uid' => '5392',
        'filename' => 'abstracts7_0312.png',
        'filepath' => 'sites/default/files/abstracts7_0312.png',
        'filemime' => 'image/png',
        'filesize' => '486116',
        'status' => '1',
        'timestamp' => '1363793808',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13259',
        'uid' => '5392',
        'filename' => 'abstracts_tb.png',
        'filepath' => 'sites/default/files/abstracts_tb_12.png',
        'filemime' => 'image/png',
        'filesize' => '13774',
        'status' => '1',
        'timestamp' => '1363793807',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '3069509',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363793809',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '57545',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363794224',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '57545',
    'revision_uid' => '1',
    'title' => 'ihad_stomission_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/ihadstomission0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13268',
        'uid' => '5392',
        'filename' => 'ihad_stomission_0313.png',
        'filepath' => 'sites/default/files/ihad_stomission_0313.png',
        'filemime' => 'image/png',
        'filesize' => '676262',
        'status' => '1',
        'timestamp' => '1363794224',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13267',
        'uid' => '5392',
        'filename' => 'ihad_stomission_tb_0313.png',
        'filepath' => 'sites/default/files/ihad_stomission_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '59820',
        'status' => '1',
        'timestamp' => '1363794224',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '736082',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363794224',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '57546',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363794461',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '57546',
    'revision_uid' => '1',
    'title' => 'ihad_pinedo2012_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/ihadpinedo20120313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13270',
        'uid' => '5392',
        'filename' => 'ihad_pinedo2012_0313.png',
        'filepath' => 'sites/default/files/ihad_pinedo2012_0313.png',
        'filemime' => 'image/png',
        'filesize' => '586568',
        'status' => '1',
        'timestamp' => '1363794461',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13269',
        'uid' => '5392',
        'filename' => 'ihad_pinedo2012_tb_0313.png',
        'filepath' => 'sites/default/files/ihad_pinedo2012_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '51057',
        'status' => '1',
        'timestamp' => '1363794461',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '637625',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363794461',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '57713',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1363961132',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '57713',
    'revision_uid' => '1',
    'title' => 'classified_alaskanative_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/classifiedalaskanative0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13342',
        'uid' => '5392',
        'filename' => 'classified_alaskanative_0313.png',
        'filepath' => 'sites/default/files/classified_alaskanative_0313.png',
        'filemime' => 'image/png',
        'filesize' => '459241',
        'status' => '1',
        'timestamp' => '1363961132',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13341',
        'uid' => '5392',
        'filename' => 'classified_alaskanative_tb_0313.png',
        'filepath' => 'sites/default/files/classified_alaskanative_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '51250',
        'status' => '1',
        'timestamp' => '1363961132',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '510491',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1363961132',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '58052',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1364231317',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '58052',
    'revision_uid' => '1',
    'title' => 'cover_ee_0313',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/coveree0313',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13401',
        'uid' => '5392',
        'filename' => 'cover1_ee_0313.png',
        'filepath' => 'sites/default/files/cover1_ee_0313.png',
        'filemime' => 'image/png',
        'filesize' => '398533',
        'status' => '1',
        'timestamp' => '1364231317',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13402',
        'uid' => '5392',
        'filename' => 'cover2_0213.png',
        'filepath' => 'sites/default/files/cover2_0213_1.png',
        'filemime' => 'image/png',
        'filesize' => '474300',
        'status' => '1',
        'timestamp' => '1364231317',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13403',
        'uid' => '5392',
        'filename' => 'cover3_0213.png',
        'filepath' => 'sites/default/files/cover3_0213_1.png',
        'filemime' => 'image/png',
        'filesize' => '578771',
        'status' => '1',
        'timestamp' => '1364231317',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13400',
        'uid' => '5392',
        'filename' => 'cover1_ee_tb_0313.png',
        'filepath' => 'sites/default/files/cover1_ee_tb_0313.png',
        'filemime' => 'image/png',
        'filesize' => '43178',
        'status' => '1',
        'timestamp' => '1364231316',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1494782',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1364231317',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '60219',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1365711344',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '60219',
    'revision_uid' => '1',
    'title' => 'sctm_cover_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmcover0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13507',
        'uid' => '5392',
        'filename' => 'sctm_cover1_0413.png',
        'filepath' => 'sites/default/files/sctm_cover1_0413.png',
        'filemime' => 'image/png',
        'filesize' => '595132',
        'status' => '1',
        'timestamp' => '1365711343',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13508',
        'uid' => '5392',
        'filename' => 'sctm_masthead_0413.png',
        'filepath' => 'sites/default/files/sctm_masthead_0413.png',
        'filemime' => 'image/png',
        'filesize' => '697988',
        'status' => '1',
        'timestamp' => '1365711343',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13506',
        'uid' => '5392',
        'filename' => 'sctm_cover1_tb_0413.png',
        'filepath' => 'sites/default/files/sctm_cover1_tb_0413.png',
        'filemime' => 'image/png',
        'filesize' => '55503',
        'status' => '1',
        'timestamp' => '1365711343',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1348623',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1365711344',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '60220',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1365711431',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '60220',
    'revision_uid' => '1',
    'title' => 'sctm_mission_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmmission0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13510',
        'uid' => '5392',
        'filename' => 'sctm_mission_0413.png',
        'filepath' => 'sites/default/files/sctm_mission_0413.png',
        'filemime' => 'image/png',
        'filesize' => '391711',
        'status' => '1',
        'timestamp' => '1365711431',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13509',
        'uid' => '5392',
        'filename' => 'sctm_mission_tb_0213.png',
        'filepath' => 'sites/default/files/sctm_mission_tb_0213_0.png',
        'filemime' => 'image/png',
        'filesize' => '31764',
        'status' => '1',
        'timestamp' => '1365711431',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '423475',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1365711431',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '60222',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1365711503',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '60222',
    'revision_uid' => '1',
    'title' => 'sctm_abstracts_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmabstracts0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13512',
        'uid' => '5392',
        'filename' => 'sctm_abstracts1_0412.png',
        'filepath' => 'sites/default/files/sctm_abstracts1_0412_0.png',
        'filemime' => 'image/png',
        'filesize' => '719229',
        'status' => '1',
        'timestamp' => '1365711502',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13513',
        'uid' => '5392',
        'filename' => 'sctm_abstracts2_0412.png',
        'filepath' => 'sites/default/files/sctm_abstracts2_0412_0.png',
        'filemime' => 'image/png',
        'filesize' => '708282',
        'status' => '1',
        'timestamp' => '1365711502',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13514',
        'uid' => '5392',
        'filename' => 'sctm_abstracts3_0412.png',
        'filepath' => 'sites/default/files/sctm_abstracts3_0412_0.png',
        'filemime' => 'image/png',
        'filesize' => '758245',
        'status' => '1',
        'timestamp' => '1365711502',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13511',
        'uid' => '5392',
        'filename' => 'sctm_abstracts_tb_0412.png',
        'filepath' => 'sites/default/files/sctm_abstracts_tb_0412_12.png',
        'filemime' => 'image/png',
        'filesize' => '29809',
        'status' => '1',
        'timestamp' => '1365711502',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '2215565',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1365711503',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '60223',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1365711620',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '60223',
    'revision_uid' => '1',
    'title' => 'sctm_news_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/sctmnews0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13516',
        'uid' => '5392',
        'filename' => 'actm_news1_0413.png',
        'filepath' => 'sites/default/files/actm_news1_0413.png',
        'filemime' => 'image/png',
        'filesize' => '670489',
        'status' => '1',
        'timestamp' => '1365711620',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13517',
        'uid' => '5392',
        'filename' => 'sctm_news2_0413.png',
        'filepath' => 'sites/default/files/sctm_news2_0413.png',
        'filemime' => 'image/png',
        'filesize' => '715526',
        'status' => '1',
        'timestamp' => '1365711620',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13518',
        'uid' => '5392',
        'filename' => 'sctm_news3_0413.png',
        'filepath' => 'sites/default/files/sctm_news3_0413.png',
        'filemime' => 'image/png',
        'filesize' => '763951',
        'status' => '1',
        'timestamp' => '1365711620',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13515',
        'uid' => '5392',
        'filename' => 'sctm_news_tb_0412.png',
        'filepath' => 'sites/default/files/sctm_news_tb_0412_11.png',
        'filemime' => 'image/png',
        'filesize' => '28625',
        'status' => '1',
        'timestamp' => '1365711619',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '2178591',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1365711620',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '61142',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1366814418',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61142',
    'revision_uid' => '1',
    'title' => 'cover_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/cover0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13638',
        'uid' => '5392',
        'filename' => 'cover1_0413.png',
        'filepath' => 'sites/default/files/cover1_0413.png',
        'filemime' => 'image/png',
        'filesize' => '377128',
        'status' => '1',
        'timestamp' => '1366814418',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13639',
        'uid' => '5392',
        'filename' => 'cover2_0413.png',
        'filepath' => 'sites/default/files/cover2_0413.png',
        'filemime' => 'image/png',
        'filesize' => '376739',
        'status' => '1',
        'timestamp' => '1366814418',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13640',
        'uid' => '5392',
        'filename' => 'cover3_0213.png',
        'filepath' => 'sites/default/files/cover3_0213_2.png',
        'filemime' => 'image/png',
        'filesize' => '578771',
        'status' => '1',
        'timestamp' => '1366814418',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13637',
        'uid' => '5392',
        'filename' => 'cover_tb_0413.png',
        'filepath' => 'sites/default/files/cover_tb_0413.png',
        'filemime' => 'image/png',
        'filesize' => '44523',
        'status' => '1',
        'timestamp' => '1366814418',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1377161',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1366814418',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '61143',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1366814822',
    'changed' => '1367445992',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61143',
    'revision_uid' => '1',
    'title' => 'abstracts_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445992',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/abstracts0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
      '3' => array(
        'value' => 'page_image',
      ),
      '4' => array(
        'value' => 'page_image',
      ),
      '5' => array(
        'value' => 'page_image',
      ),
      '6' => array(
        'value' => 'page_image',
      ),
      '7' => array(
        'value' => 'page_image',
      ),
      '8' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13642',
        'uid' => '5392',
        'filename' => 'abstracts1_0413.png',
        'filepath' => 'sites/default/files/abstracts1_0413.png',
        'filemime' => 'image/png',
        'filesize' => '438173',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13643',
        'uid' => '5392',
        'filename' => 'abstracts2_0413.png',
        'filepath' => 'sites/default/files/abstracts2_0413.png',
        'filemime' => 'image/png',
        'filesize' => '476215',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13644',
        'uid' => '5392',
        'filename' => 'abstracts3_0413.png',
        'filepath' => 'sites/default/files/abstracts3_0413.png',
        'filemime' => 'image/png',
        'filesize' => '450744',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '3' => array(
        'fid' => '13645',
        'uid' => '5392',
        'filename' => 'abstracts4_0413.png',
        'filepath' => 'sites/default/files/abstracts4_0413.png',
        'filemime' => 'image/png',
        'filesize' => '455717',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '4' => array(
        'fid' => '13646',
        'uid' => '5392',
        'filename' => 'abstracts6_0413.png',
        'filepath' => 'sites/default/files/abstracts6_0413.png',
        'filemime' => 'image/png',
        'filesize' => '374400',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '5' => array(
        'fid' => '13647',
        'uid' => '5392',
        'filename' => 'abstracts6_0413.png',
        'filepath' => 'sites/default/files/abstracts6_0413_0.png',
        'filemime' => 'image/png',
        'filesize' => '374400',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '6' => array(
        'fid' => '13648',
        'uid' => '5392',
        'filename' => 'abstracts7_0413.png',
        'filepath' => 'sites/default/files/abstracts7_0413.png',
        'filemime' => 'image/png',
        'filesize' => '511180',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '7' => array(
        'fid' => '13649',
        'uid' => '5392',
        'filename' => 'abstracts8_0413.png',
        'filepath' => 'sites/default/files/abstracts8_0413.png',
        'filemime' => 'image/png',
        'filesize' => '496877',
        'status' => '1',
        'timestamp' => '1366814822',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '8' => array(
        'fid' => '13650',
        'uid' => '5392',
        'filename' => 'abstracts9_0413.png',
        'filepath' => 'sites/default/files/abstracts9_0413.png',
        'filemime' => 'image/png',
        'filesize' => '234422',
        'status' => '1',
        'timestamp' => '1366814822',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13641',
        'uid' => '5392',
        'filename' => 'abstracts_tb.png',
        'filepath' => 'sites/default/files/abstracts_tb_13.png',
        'filemime' => 'image/png',
        'filesize' => '13774',
        'status' => '1',
        'timestamp' => '1366814821',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '3825902',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1366814822',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '61144',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1366815574',
    'changed' => '1367445993',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61144',
    'revision_uid' => '1',
    'title' => 'editors_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445993',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/editors0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13652',
        'uid' => '5392',
        'filename' => 'editors1_0413.png',
        'filepath' => 'sites/default/files/editors1_0413.png',
        'filemime' => 'image/png',
        'filesize' => '480864',
        'status' => '1',
        'timestamp' => '1366815574',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13653',
        'uid' => '5392',
        'filename' => 'editors2_0413.png',
        'filepath' => 'sites/default/files/editors2_0413.png',
        'filemime' => 'image/png',
        'filesize' => '460686',
        'status' => '1',
        'timestamp' => '1366815574',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13651',
        'uid' => '5392',
        'filename' => 'editors_tb.png',
        'filepath' => 'sites/default/files/editors_tb_14.png',
        'filemime' => 'image/png',
        'filesize' => '13461',
        'status' => '1',
        'timestamp' => '1366815574',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '955011',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1366815574',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
    array(
    'nid' => '61611',
    'type' => 'article',
    'language' => '',
    'uid' => '5392',
    'status' => '1',
    'created' => '1367331947',
    'changed' => '1367445993',
    'comment' => '0',
    'promote' => '1',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '0',
    'translate' => '0',
    'vid' => '61611',
    'revision_uid' => '1',
    'title' => 'cover_ee_0413',
    'body' => '',
    'teaser' => '',
    'log' => '',
    'revision_timestamp' => '1367445993',
    'format' => '0',
    'name' => 'lauren.deans@alphamedpress.com',
    'picture' => '',
    'data' => 'a:1:{s:7:"contact";i:0;}',
    'path' => 'content/articles/coveree0413',
    'field_page_type' => array(
      '0' => array(
        'value' => 'page_image',
      ),
      '1' => array(
        'value' => 'page_image',
      ),
      '2' => array(
        'value' => 'page_image',
      ),
    ),
    'field_image_portrait' => array(
      '0' => array(
        'fid' => '13719',
        'uid' => '5392',
        'filename' => 'cover1_ee_0413.png',
        'filepath' => 'sites/default/files/cover1_ee_0413_0.png',
        'filemime' => 'image/png',
        'filesize' => '414624',
        'status' => '1',
        'timestamp' => '1367331917',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '1' => array(
        'fid' => '13720',
        'uid' => '5392',
        'filename' => 'cover2_0413.png',
        'filepath' => 'sites/default/files/cover2_0413_0.png',
        'filemime' => 'image/png',
        'filesize' => '376739',
        'status' => '1',
        'timestamp' => '1367331918',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
      '2' => array(
        'fid' => '13722',
        'uid' => '5392',
        'filename' => 'cover3_0213.png',
        'filepath' => 'sites/default/files/cover3_0213_3.png',
        'filemime' => 'image/png',
        'filesize' => '578771',
        'status' => '1',
        'timestamp' => '1367331946',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_thumbnail' => array(
      '0' => array(
        'fid' => '13721',
        'uid' => '5392',
        'filename' => 'template_ipad_size.png',
        'filepath' => 'sites/default/files/template_ipad_size.png',
        'filemime' => 'image/png',
        'filesize' => '47676',
        'status' => '1',
        'timestamp' => '1367331946',
        'origname' => '',
        'list' => '1',
        'data' => array(
          'alt' => '',
          'title' => '',
        ),
      ),
    ),
    'field_socialmedialink' => array(
      '0' => array(
        'url' => NULL,
        'title' => NULL,
        'attributes' => FALSE,
      ),
    ),
    'field_article_downloadsize' => array(
      '0' => array(
        'value' => '1417810',
      ),
    ),
    'field_crestriction_enabled' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_crestriction_negate' => array(
      '0' => array(
        'value' => '0',
      ),
    ),
    'field_reference_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_interactive_ad' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_image_horizontal' => array(
      '0' => NULL,
    ),
    'field_reference_video' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_mutablevideo' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_reference_int_html' => array(
      '0' => array(
        'nid' => NULL,
      ),
    ),
    'field_crestriction_list' => array(
      '0' => array(
        'value' => NULL,
      ),
    ),
    'last_comment_timestamp' => '1367331947',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'nodewords' => array(),
    'menu' => array(
      'link_title' => '',
      'mlid' => 0,
      'plid' => 0,
      'menu_name' => 'primary-links',
      'weight' => 0,
      'options' => array(),
      'module' => 'menu',
      'expanded' => 0,
      'hidden' => 0,
      'has_children' => 0,
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    'export_display' => '$display = new ;
$display->layout = \'\';
$display->layout_settings = \'\';
$display->panel_settings = \'\';
$display->cache = \'\';
$display->title = \'\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \'0\';
',
    '#_export_node_encode_object' => '1',
  ),
);
}